### ISSUE TITLE
lxml dependency

### ISSUE THREAD

**Issue by zerogerc** [bionlplab/bioc#10]
First of all, great library. Thank you for you work.

I'm wondering is there a strict requirement for `lxml=4.4.1`. Or could it be more flexible like `lxml>=4.4.1`.  It doesn't seem like `lxml` introduced breaking changes https://lxml.de/4.5/changes-4.5.0.html, but it would be really helpful in projects with multiple dependencies which can conflict.

**Comment by yfpeng** [comment]
Thanks for your suggestions. I have changed them.

**Comment by haobibo** [comment]
Hi @yfpeng looking forward to seeing the change in both https://github.com/bionlplab/bioc/blob/master/setup.py and on pypi

**Comment by yfpeng** [comment]
Will do. For your amusement,  ``pip install bioc --no-dep`` will do the trick.
