### ISSUE TITLE
Can't use 'with' with BioCXMLDocumentReader

### ISSUE THREAD

**Issue by jakelever** [bionlplab/bioc#11]
Hi, the new release has stopped the use of BioCXMLDocumentReader using a 'with' statement. It looks like the \_\_enter\_\_ and \_\_exit\_\_ methods were removed in commit 8174c1dcd3502a81a82dea2781e1a7997c3fd117. The documentation still suggests that you can do it that way. It'd be really useful if this could be reintroduced.

Here's a short bit of example code that gives the error below it.

```python
import bioc
with bioc.BioCXMLDocumentReader('test.bioc.xml') as reader:
        pass
```

```
Traceback (most recent call last):
  File "itertest.py", line 3, in <module>
    with bioc.BioCXMLDocumentReader('test.bioc.xml') as reader:
AttributeError: __enter__
```

**Comment by yfpeng** [comment]
Thank you. I have changed the README.
