### ISSUE TITLE
Normalized datasets fail during parsing

### ISSUE THREAD

**Issue by shamikbose** [bionlplab/bioc#16]
For datsaets like tmVar v2.0, pubtator fails due to the presence of the "RSID: xxxxxxxxx" at the end of the annotations. Example file here: https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/download/tmVar/tmVar.Normalization.txt

**Comment by yfpeng** [comment]
Which PMID does not work?

**Comment by yfpeng** [comment]
Fixed it in 2.0.post4.
