### ISSUE TITLE
Relations in pubtator not showing

### ISSUE THREAD

**Issue by shamikbose** [bionlplab/bioc#18]
I'm trying to read the BioRED file from here: https://ftp.ncbi.nlm.nih.gov/pub/lu/BioRED/
As you will see, it has pubtator formats. The annotations are read in propely, but when I try to read the relations, it doesn't provide any output
The relations are written as follows:

```14510914	Positive_Correlation	c|DEL|1314_1328|	D003409	Novel
14510914	Association	D050033	D007454	No
14510914	Positive_Correlation	p|DEL|439_443|	C564766	Novel
14510914	Positive_Correlation	p|DEL|439_443|	D003409	Novel
14510914	Association	C564766	D007454	No
```
Is this something `bioc.pubtator` supports?

**Comment by yfpeng** [comment]
Thanks. Please try v2.0.post5
