### ISSUE TITLE
Convert BioC to  brat?

### ISSUE THREAD

**Issue by serenalotreck** [bionlplab/bioc#22]
I have a BioC formatted dataset that I'd like to be able to use in brat. I looked at the code for `brat2bioc` and it looks like there's no way to convert in the opposite direction; however, in the [brat2bioc tech report](https://biocreative.bioinformatics.udel.edu/media/store/files/2013/bc4_v1_7.pdf) it says that the original code in java allowed conversion in both directions ("that translates annotations originally in brat format into BioC and vice versa").

Is there a way to bring this functionality into the python module?

EDIT: spelling

**Comment by yfpeng** [comment]
We don't provide a reverse conversion.
